# -*- coding: utf-8 -*-
"""Hollywood Theatrical Market Synopsis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10FfWT-q1FLR0qvrVi1qiUFGL_GKCm5Up
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive/')
# %cd /gdrive

ls

cd/gdrive/My Drive/Theatrical Market Synopsis/

ls

"""Import Dependencies"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Reading CSV file"""

TopProductionMethod = pd.read_csv("TopProductionMethods.csv");
TopDistributors = pd.read_csv("TopDistributors.csv");
TopGenres = pd.read_csv("TopGenres.csv");
PopularCreativeTypes = pd.read_csv("PopularCreativeTypes.csv");
TopGrossingRatings = pd.read_csv("TopGrossingRatings.csv");
TopGrossingSources = pd.read_csv("TopGrossingSources.csv");
HighestGrossers = pd.read_csv("HighestGrossers.csv");
AnnualTicketSales = pd.read_csv("AnnualTicketSales.csv",thousands = ',');
WideReleasesCount = pd.read_csv("WideReleasesCount.csv");

"""Annual Ticket sale"""

AnnualTicketSales.head()

AnnualTicketSales['TOTAL BOX OFFICE'] = AnnualTicketSales['TOTAL BOX OFFICE'].str.replace(',', '')
AnnualTicketSales['TOTAL BOX OFFICE'] = AnnualTicketSales['TOTAL BOX OFFICE'].str.replace('$', '')
AnnualTicketSales['TOTAL INFLATION ADJUSTED BOX OFFICE'] = AnnualTicketSales['TOTAL INFLATION ADJUSTED BOX OFFICE'].str.replace(',', '')
AnnualTicketSales['TOTAL INFLATION ADJUSTED BOX OFFICE'] = AnnualTicketSales['TOTAL INFLATION ADJUSTED BOX OFFICE'].str.replace('$', '')
AnnualTicketSales['AVERAGE TICKET PRICE'] = AnnualTicketSales['AVERAGE TICKET PRICE'].str.replace('$', '')
AnnualTicketSales.drop('Unnamed: 5', axis = 1 , inplace = True)

AnnualTicketSales.head()

AnnualTicketSales["TOTAL BOX OFFICE"] = AnnualTicketSales["TOTAL BOX OFFICE"].astype(str).astype(int)

AnnualTicketSales.info()

AnnualTicketSales.isnull().sum()

ax = sns.catplot(y="TICKETS SOLD", x="YEAR", kind="bar", data=AnnualTicketSales, height=6, aspect=3)
plt.ylabel("TICKETS SOLD in billion")
plt.grid(True)

AnnualTicketSales.plot.bar(x='YEAR',y='TOTAL BOX OFFICE')
plt.ylabel("TICKETS SOLD in billion")
plt.grid(True)

"""Highest Grossers"""

HighestGrossers.head()

HighestGrossers['TOTAL FOR YEAR'] = HighestGrossers['TOTAL FOR YEAR'].str.replace(',', '')
HighestGrossers['TOTAL FOR YEAR'] = HighestGrossers['TOTAL FOR YEAR'].str.replace('$', '')
HighestGrossers["TOTAL FOR YEAR"] = HighestGrossers["TOTAL FOR YEAR"].astype(str).astype(int)

df1 = pd.DataFrame(HighestGrossers, columns = ['MOVIE','TOTAL FOR YEAR'])
df1.sort_values(by=['TOTAL FOR YEAR'], ascending = False,inplace=True)

"""Top 10 movie of all time by total earning"""

plt.pie(df1['TOTAL FOR YEAR'][0:10],labels = df1['MOVIE'][0:10],autopct='%1.1f%%',explode = (0.05,0.05, 0.1,0.05,0.05,0.05,0.05,0.05,0.05,0.05),radius=3,shadow=True)
plt.show()

"""Top Genres"""

TopGenres

TopGenres['TOTAL GROSS'] = TopGenres['TOTAL GROSS'].str.replace(',', '')
TopGenres['TOTAL GROSS'] = TopGenres['TOTAL GROSS'].str.replace('$', '')
TopGenres["TOTAL GROSS"] = TopGenres["TOTAL GROSS"].astype(str).astype(int)

ax = sns.catplot(y="TOTAL GROSS", x="GENRES", kind="bar", data=TopGenres, height=6, aspect=3)
plt.ylabel("TOTAL GROSS ")
plt.title("Popular Genres")

